### ISSUE TITLE
Report-Generator kann nicht aufgerufen werden

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#135]
@JakobBenkoe woran liegt das? Es wird ja kompiliert

**Comment by JakobBenkoe** [comment]
geht bei mir mit: https://meta-yen-229220.appspot.com/ReportGenerator.html

**Comment by JakobBenkoe** [comment]
geht bei mir mit: https://meta-yen-229220.appspot.com/ReportGenerator.html
