### ISSUE TITLE
Like kann entfertn werden durch anderen Nutzer

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#156]

**Comment by AdamGniady** [comment]
Anscheinend ist UserFK immer

**Comment by AdamGniady** [comment]
Das ist gelöst oder @GianlucaBernert ?

**Comment by GianlucaBernert** [comment]
Ja jetzt müsste alles passen auch mit dem Wechsel der Herzen müsste jetzt alles Funktionieren.

Einzige was ich noch nicht gemacht habe ist der Button Wechsel aber wenn ihr das auch wollte dann kann ich das da auch noch rein machen ist ja schnell Erledigt. 

Ich Commite es jetzt mal dann könnt ihr euch das Anschauen
