### ISSUE TITLE
impl.createBeitrag() setzt nicht die dazugehörige Pinnwand, nur den User!

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#57]
Nach DB Sicht + BO codierung sollte die Pinnwand auch gespeichert werden

**Comment by SebastianHermann** [comment]
Issue behoben. Da jedem User genau eine Pinnwand zugewiesen ist, ist nun lediglich der User zu setzen. In der Impl wird nun sichergestellt, dass Pinnwand und User immer konsistent ist, in dem die Pinnwand des gesetzten Users in der Methode aufgerufen wird.

**Comment by AdamGniady** [comment]
Hast du das schon gepusht? Sehe keine neuen Commits

**Comment by AdamGniady** [comment]
Wenn du das korrigiert hast push es bitte, funktioniert noch nicht

**Comment by SebastianHermann** [comment]
ist seit gestern gepusht, bei mir funktioniert es.

**Comment by UlusSerhat** [comment]
`impl.createBeitrag("hallo", impl.getUserById(1), timestamp);`
