### ISSUE TITLE
Pinnwand suche nach UserId nicht möglich

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#61]
Momentan nur Suche nach User und dessen zugehörige Beiträge, Kommentare, etc. 

Ggf. müsste das auch erst nochmal in den Mappern integriert werden.

**Comment by UlusSerhat** [comment]
`impl.getPinnwandByUserId(1);`

Die Pinnwand anhand der UserId zu suchen funktioniert
