### ISSUE TITLE
findAllKommentareOfBeitrag funktioniert nicht

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#63]
Es gibt einen SQL Syntax Fehler. Ich glaube es liegt daran, dass im Mapper momentan ein falsches SQL Statement steht. 
Dort steht momentan: 

`"SELECT * FROM kommentar" +"WHERE BeitragFK=" +"'"+ beitragId+ "'" + "ORDER BY KommentarID"`

Dies ist mindestens BeitragID zuviel. Folgendes SQL Statement funktioniert jedenfalls problemlos in der MySQL Query Konsole:
`SELECT * FROM pinners.kommentar WHERE BeitragFK=3 ORDER BY KommentarID`

**Comment by UlusSerhat** [comment]
`ResultSet rs = stmt.executeQuery("SELECT * FROM `kommentar` WHERE BeitragFK="+ beitragId );` 
Zeile 194
