### ISSUE TITLE
deleteBeitrag funktioniert nicht

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#66]
Könnte daran liegen, dass die deleteKaskade die dazugehört (deleteBeiträge, deleteKommentar) noch nicht richtig implementiert ist?

**Comment by UlusSerhat** [comment]
`Beitrag b = new Beitrag();			
	        b.setBeitragId(1);
		b.setOwnerId(1);
		b.setPinnwandId(1);
		
		impl.deleteBeitrag(b);`
