### ISSUE TITLE
SQL Fehler bei deleteLike

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#67]
Momentan kann man die Likes nicht löschen. 
Erster Gedanke war fehlende ID => war richtig, jedoch nicht die Lösung, da es trotz richtiger ID nicht gelöscht wird. Wenn ich das ausgegebene SQL-Statement (über Sysout hab ich es mir ausgeben lassen) in der MySQL-Konsole eingebe funktioniert es. **ULTRA WEIRD**

**Comment by AdamGniady** [comment]
Habe im Moment aber auch keine Idee woran es liegen könnte, da es über die Konsole funktioniert. 
Ganz schön seltsam

**Comment by UlusSerhat** [comment]
`Like l1 = new Like();
	         l1.setLikeId(1);
		l1.setBeitragId(1);
		l1.setOwnerId(1);
		
		
	impl.deleteLike(l1);`

Likes konnten so nun gelöscht werden
