### ISSUE TITLE
createLike() funktioniert nicht

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#69]
Man kann den User setzen und das SQL Statement sieht eigentlich auch korrekt aus, jedoch kann kein Like created werden

**Comment by UlusSerhat** [comment]
`impl.createLike(impl.getUserById(1), impl.getBeitragById(1), timestamp);`

**Comment by UlusSerhat** [comment]
`impl.createLike(impl.getUserById(1), impl.getBeitragById(1), timestamp);`
