### ISSUE TITLE
showAllUser hat ein Typo im Mapper

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#71]
Zum einen steht dort: ORDED statt ORDER By
zum anderen steht dort Nachname statt Lastname. 

Ändert man die Typos funktioniert es

**Comment by UlusSerhat** [comment]
Die Methode "showAllUser" ist bei mir im UserMapper nicht enthalten

**Comment by UlusSerhat** [comment]
`ResultSet rs = stmt.executeQuery("SELECT * FROM user WHERE lastName= '" + lName +"'"+ " ### ORDER BY lastName");
	
				
				while (rs.next()) {
					User u = new User();
					u.setUserId(rs.getInt("UserID"));
					u.setNickname(rs.getString("Nickname"));
					u.setFirstName(rs.getString("Firstname"));
					u.setLastName(rs.getString("**Lastname**"));`
