### ISSUE TITLE
searchUserByNickName hat einen Typo

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#73]
Auch hier ist noch "Nachname" statt "Lastname" drin. Bei Änderung sollte es eigentlich funktionieren.

**Comment by UlusSerhat** [comment]
Es muss doch Nickname rein statt Nachname

`public User searchUserByNickname(String nickname) {
		// TODO Auto-generated method stub
		return null;`

**Comment by UlusSerhat** [comment]
`/*
	 * Methode, die einen User anhand des Nachnamen zurueck gibt
	 */		
		public Vector<User> **findUserByLastName**(String lName) {
			Connection con = DBConnection.connection();
			Vector<User> result = new Vector<User>();
	`
