### ISSUE TITLE
findAllBeitraegeOfUser hat eine Fehlerhafte Mapperfunktion

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#74]
Es fehlt das "Where" keyword im SQL aufruf des Mappers

**Comment by UlusSerhat** [comment]
try {
	Statement stmt = con.createStatement();
				
ResultSet rs = stmt.executeQuery("SELECT * FROM beitrag **WHERE** UserFK= " + userFK);
