### ISSUE TITLE
{findUserById()} toString() der Klasse BusinessObject zeigt die BO-ID immer 0 an

### ISSUE THREAD

**Issue by GianlucaBernert** [AdamGniady/SWP_WS1819_Gruppe1#75]
Beim Ausgeben des Ergebnisses wird zwar der richtige User angezeigt jedoch immer mit BO-ID #0

**Comment by AdamGniady** [comment]
Das ist kein Fehler der Methode, das ist doch der ein ToString() Fehler

**Comment by GianlucaBernert** [comment]
Ja der toString() fehler ist in der Klasse BusinessObject da setzt der ja die ID die wir da sehen und der setzt immer die des BusinessObjects und diese ist hier scheinbar 0

**Comment by GianlucaBernert** [comment]
toString() in der Klasse BusinessObject und User geändert passe die in den anderen bo Klassen auch gleich an
