### ISSUE TITLE
LikeCheck hat einen SQL-Syntaxfehler + falscher Rückgabewert?

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#76]
Im SQL Statement steht ein "&" statt des wortes AND, welches bei SQL genutzt werden muss. 
Sollte auch der Rückgabewert nicht ein Boolean sein wie du meintest @SebastianHermann ?
Wäre sinnvoller oder?

**Comment by UlusSerhat** [comment]
`try {
				Statement stmt = con.createStatement();
					
				// Statement ausfuellen und als Query an die DB schicken
				ResultSet rs = stmt.executeQuery("SELECT * FROM `like` WHERE UserFK=" + userId + " **AND** BeitragFK=" + beitragId);`
