### ISSUE TITLE
deleteLikesOfBeitrag() funktioniert nicht

### ISSUE THREAD

**Issue by AdamGniady** [AdamGniady/SWP_WS1819_Gruppe1#77]
Generell überall wo Likes sind, gibt es Probleme.
Es wirft eine SQL Exception --> Wahrscheinlich Mapper Fehlerhaft

**Comment by UlusSerhat** [comment]
Mapper stimmt müsste funktionieren.

Habe das selbst geteset: `Beitrag b = new Beitrag();
		b.setBeitragID(5);
		b.setOwnerId(3);
	
		impl.deleteLikesOfBeitrag(b);`
